#!/usr/bin/python
__author__ = "Theo Martos"

import os

print("Compiling...")
res = os.system("javac -d ./bin -cp :./lib/twitter4j.jar:./src src/client/*.java")
if(res == 0):
    print("Starting...")
    cmd = "cd ./bin && java -cp :../lib/twitter4j.jar:../src Indexor"
    os.system(cmd)
else:
    print('Compilation failed, start aborded')
