#!/usr/bin/python
__author__ = "Theo Martos"

import os

print("Compiling...")
res = os.system("javac -d ./bin -cp :./lib/twitter4j.jar:./lib/twitter4j-stream.jar:./lib/gson.jar:./src ./src/RunCrawler.java")
if(res == 0):
    print("Starting...")
    os.system("cd ./bin && java -cp :../lib/twitter4j.jar:../lib/twitter4j-stream.jar:../lib/gson.jar:../src RunCrawler")
else:
    print('Compilation failed, start aborded')
