#!/usr/bin/python
__author__ = "Theo Martos"

import os

print("Compiling...")
res = os.system("javac -d ./bin/client -cp :./lib/twitter4j.jar src/client/*.java")
if(res == 0):
    print("Starting...")
    cmd = "cd ./bin/client && java -cp :../lib/twitter4j.jar Indexor adalannvps.fr"
    os.system(cmd)
else:
    print('Compilation failed, start aborded')
