#!/usr/bin/python
__author__ = "Theo Martos"

import os

if not os.path.exists('bin'):
    os.mkdir('bin')

print("Compiling...")
res = os.system("javac -d ./bin -cp :./lib/twitter4j.jar:./lib/gson.jar:./src ./src/RunIndexor.java")
if(res == 0):
    print("Starting...")
    os.system("cd ./bin && java -cp :../lib/twitter4j.jar:../lib/gson.jar:../src RunIndexor")
else:
    print('Compilation failed, start aborded')
